name: Test

env:
  NODE_OPTIONS: --max-old-space-size=6144
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
  VITEST_SEGFAULT_RETRY: 3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit packages
        run: npm audit --audit-level moderate
        env:
          CI: true
